### PR TITLE
revert $(NAME)_emu to $(NAME) for host target executable

### PR DESCRIPTION
**Pull request by lowagner**
if you want to keep it how we had it in v0.8

### CODE REVIEW

**Comment by makapuf** [comment]
In fact I think this is better kept with _emu. IIUC  the goal for removing _emu was to ease running the program on the commandline. Well, since all targets should not be executable apart from this one, my shell only expands ./xxx to the emu target (assuming _test is not built, which is not very often).
But keeping _emu allows to have  *_emu in gitgnore by example.

**Comment by lowagner** [comment]
no problem, it is merely cosmetic.  and you're right, my shell also expands out quickly and correctly.  were some of the .bin's being chmod+x'ed earlier, but now they're not?

**Comment by makapuf** [comment]
yup, that's from commit id 9f19c43

2016-01-25 22:55 GMT+01:00 Lucas O. Wagner <notifications@github.com>:

**Comment by lowagner** [comment]
very nice, that should do just fine.

**Pull request closed without merging**
