### PR TITLE
can now make a O1 -DDEBUG host (emulator) version with "make debug"

### PR DESCRIPTION
**Pull request by lowagner**
it also creates the debug bin file, if possible.

(on my computer, I can't build the debug bin file:
/bin/sh: 1: arm-none-eabi-gdb: not found
but maybe i don't have something linked properly.)

this way we can also take out the -g option from the standard make, if we want.

### CODE REVIEW

**Comment by makapuf** [comment]
I like it ! what about using -Og instead ? 

as Gcc realease notes for 4.8 says  :
A new general optimization level, -Og, has been introduced. It addresses the need for fast compilation and a superior debugging experience while providing a reasonable level of run-time performance. Overall experience for development should be better than the default optimization level -O0.

**Comment by lowagner** [comment]
i was thinking of debugging mostly for the emulator version, and -Og is fine with me there.  i'm not always aware of "best Makefile practices".

we can do something like this (though whatever you think is best...)
```
debug:  ALL_CFLAGS := $(filter-out -O3, $(ALL_CFLAGS)) -DDEBUG -Og
debug:  clean $(NAME)

bin-debug: $(NAME).elf
▸   arm-none-eabi-gdb $(NAME).elf \
▸   --eval-command="target extended-remote :4242"
```

**Comment by lowagner** [comment]
how about this:  keep -O3 for the binary, and -Og for the emulator (apparently it already was doing this and i didn't realize how the emulator was built), but add in profiling for the bitbox and the debug flag for both.

```
# build a debug binary and debug emulator here:
debug:  
▸   $(MAKE) M=`pwd` debug-bin 
▸   $(MAKE) M=`pwd` debug-emu   

# for debug binary, build with profiling and debugging:
debug-bin:  ALL_CFLAGS += -DDEBUG -DPROFILE
debug-bin:  clean $(NAME).bin

# and build a host executable with debug flag:
debug-emu:  GAME_C_OPTS += -DDEBUG
debug-emu:  $(NAME)
```

**Comment by lowagner** [comment]
rebased my version to avoid changing the debug stuff.

**Pull request closed without merging**
