### PR TITLE
fix for SNES joypads (pressing dpad) plugged into SDL emulator

### PR DESCRIPTION
**Pull request by lowagner**
apparently gamepad_x and gamepad_y do nothing to change the gameplay, so here is an option...

### CODE REVIEW

**Comment by lowagner** [comment]
rebased so it will go on the end of your new commits.

**Comment by makapuf** [comment]
we will need to study this one a bit deeper, since a snes gamepad works for
me.

2017-05-09 15:30 GMT+02:00 Lucas O. Wagner <notifications@github.com>:

**Comment by pulkomandy** [comment]
Which game did you test with? gamepad_x/y are visible in test_input IIRC. They are not buttons but analogue values, so they are drawn with a cursor inside a rectangle.
Wether games use them is another problem, but not something to workaround in the emulator?

**Comment by lowagner** [comment]
ok, well we can take out the "doesn't do anything" part.  

there are no gamepad_up/down etc. for the SNES pad i'm using, so it's nice to make it consistent between the emulator and the bitbox versions.  (on the bitbox, the SNES pad works fine with up/down/etc., but without this change the emulator doesn't use the input.)

**Comment by makapuf** [comment]
I guess this come from the *ultra clever* bitbox USB driver (not) in https://github.com/makapuf/bitbox/blob/master/kernel/StdPeriph/usbh_hid_gamepad.c#L175 : when there is no hat switch and we have directional gamepad_x and y, just fake it. So we could do that (but just in case there are no real gamepad hat to impersonate)

**Comment by lowagner** [comment]
is there a way to add a HAT_NOT_DPAD define which toggles this behavior (for both bitbox and emulator)?  it would be nice to be consistent between bitbox and emulator...

i.e., if HAT_NOT_DPAD is defined, only gamepad_x/y are updated and not gamepad_up/down on gamepad_buttons.

**Comment by makapuf** [comment]
I'd rather use int SDL_JoystickNumHats(SDL_Joystick *joystick); or related functions to check for hats dynamically

**Comment by makapuf** [comment]
Will close but is implemented in commit 0974fd5e1c0db0f572

**Comment by lowagner** [comment]
works for me.  thanks for your help!

**Pull request closed without merging**
