### PR TITLE
put sdl2 and sdl1 side by side in emulator.c, try SDL2=1 in your Makefile

### PR DESCRIPTION
**Pull request by lowagner**
sdl2 is not default (you need to put SDL2=1 in your project Makefile), but eventually we could make it the default for non-Haiku platforms, once it is bug free.

currently no keyboard input works for SDL2, but scaling is nice.

### CODE REVIEW

**Comment by lowagner** [comment]
if you want, you can use this as a base to split sdl1 and sdl2 from each other, and organize the bitbox.mk as you like.  

i've also switched to CCM_MEMORY.

**Comment by makapuf** [comment]
Hi, I haven't merged it yet - not from a lack ot will but of time !

**Comment by lowagner** [comment]
the latest commit ensures that you won't flash 2nd_boot when in the 2nd_boot menu :)

**Comment by makapuf** [comment]
Hi I've partially applied this , but needed to split diofferent commits as they're quite different in scope. concerning 2nd_boot, maybe it would be better to either have a separate format for loadable bins (including icons by example) or a different 2nd_boot extension ?

**Comment by lowagner** [comment]
you mean, switch 2nd_boot.bin to 2nd_boot.bbx or something?

i think that any of the above solutions seem pretty much equivalent, in
terms of efficiency and end-user interaction, but maybe i'm
misunderstanding something.

thanks for the work on sdl2, i'll reset my sdk so i can be even with you.

On Tue, Mar 8, 2016 at 6:20 PM, makapuf <notifications@github.com> wrote:

> Hi I've partially applied this , but needed to split diofferent commits as
> they're quite different in scope. concerning 2nd_boot, maybe it would be
> better to either have a separate format for loadable bins (including icons
> by example) or a different 2nd_boot extension ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/makapuf/bitbox/pull/58#issuecomment-194034215>.
>



-- 
"""
  lucas o. wagner
  lowagner.github.io
"""

**Comment by makapuf** [comment]
> > concerning 2nd_boot, maybe it would be
> > better to either have a separate format for loadable bins (including icons
> > by example) or a different 2nd_boot extension ?
> >

> you mean, switch 2nd_boot.bin to 2nd_boot.bbx or something?
>
> i think that any of the above solutions seem pretty much equivalent, in
> terms of efficiency and end-user interaction, but maybe i'm
> misunderstanding something.

Having a proper bbx file format for program bins (not 2ndboot) would
simplify copying a program to the SD card / dfu-util :

 - no need to put a separate icon file
 - ability to check the hardware version to run on - micro, std bitbox
- by embedding this info,
 - ability to add a small info text in the binary
 - ability to embed data after the binary to allow reading on the fly
or modifying data in the program (highscores ..)

and some datafiles could be called .bin without risking flashing them
(I tried flashing a big 70M video file once ...)

that format would not allow flashing it directly with st-flash - not
an issue, if you have a swd adapter you generally can compile from
source or we can make a tiny script to extract .bin , display text and
flash using USB using dfu-util or st-flash.

the bbx file format could be by example :
- 16B header : "BBOX" + fileversion + (reserved)
- 256B file_toc : 64x32bit records : (8bit record type + 24 bits
offset in file).

record types :
 - Hardware Target (needed RAM, needed runtime capabilities such as SD, ...)
 - text description
 - icon_type (128x128 b&w, 64x64 @ 4bpp) + icon_data
 - bin file for std bitbox
 - bin file for micro bitbox
 - other data : as defined by application but can be any resources to
load in RAM during prog execution - sound, animations, ...

**Pull request closed without merging**
